
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: org.example.log_in2.podo
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: "123456"
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: mysql
